language: python
python: sudo docker-compose run   app sh -c "python manage.py test"to docker
  - "3.7"
services:
  - docker

before_script: pip install docker-compose

script:
  - sudo docker-compose run app sh -c "python manage.py test && flake8"