language: python
python:
  - "3.7"
services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $alexasha992 --3379219Kate))-stdin

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"