version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: python:3.7-alpine
        
    steps:
      - checkout
      - run: pip install docker-compose
  test:
    docker:
      - image: python:3.7-alpine
      - checkout
      - run: sudo docker-compose run app sh -c "python manage.py test && flake8"

# Orchestrate our job run sequences
workflows:
  build_and_test:
    jobs:
      - build
      - test