version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: python:3.7-alpine
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/AlexashaAle/recipe-app-api/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  recipe_app_api:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
           docker-compose run app sh -c "python manage.py test && flake8"

workflows:
  my-custom-workflow:
    jobs:
      - recipe_app_api
